include "darkrp_properties/sh_properties.lua"
include "darkrp_properties/sh_config.lua"
include "darkrp_properties/sv_properties.lua"
include "darkrp_properties/sv_spawnnpcs.lua"
include "weapons/property_tool/shared.lua"
--include "weapons/gmod_tool/stools/property.lua"

AddCSLuaFile "darkrp_properties/sh_properties.lua"
AddCSLuaFile "darkrp_properties/sh_config.lua"
AddCSLuaFile "darkrp_properties/cl_properties.lua"
AddCSLuaFile "weapons/property_tool/shared.lua"
--AddCSLuaFile "weapons/gmod_tool/stools/property.lua"